analytics:
  target_shares_per_episode: 100
  target_views_per_episode: 1000
platforms:
  qiita:
    api_token: YOUR_QIITA_TOKEN
    auto_publish: false
    enabled: true
    organization: ''
  twitter:
    access_token: YOUR_ACCESS_TOKEN
    access_token_secret: YOUR_ACCESS_TOKEN_SECRET
    api_key: YOUR_TWITTER_API_KEY
    api_secret: YOUR_TWITTER_API_SECRET
    enabled: true
  zenn:
    auto_publish: false
    enabled: true
    username: YOUR_ZENN_USERNAME
schedule:
  publication_day: 1
  publication_time: '09:00'
  timezone: Asia/Tokyo